export enum MessageType {
	AUTH_ERROR = '@pi:app:error:auth',
	UNKNOWN_ERROR = '@pi:app:error:unknown',
	OPEN_APP_CONVERSATION_WITH_ID = '@pi:app:conversation:open_with_id',
	OPEN_SHARE_DIALOG_ACTION = '@pi:app:share_dialog:open',
	PREPARE_PAYMENT_FLOW = '@pi:app:payments:prepare_payment_flow',
	SHOW_PRE_PAYMENT_ERROR = '@pi:app:payments:show_pre_payment_error',
	START_PAYMENT_FLOW = '@pi:app:payments:start_payment_flow',
	WAIT_FOR_TRANSACTION = '@pi:app:payments:wait_for_transaction',
	COMMUNICATION_INFORMATION_REQUEST = '@pi:app:sdk:communication_information_request',
	OPEN_CONSENT_MODAL = '@pi:app:sdk:open_consent_modal',
	CHECK_NATIVE_FEATURES = '@pi:app:sdk:check_native_features',
	DECIDE_CALLBACK_RETRIAL = '@pi:app:sdk:decide_callback_retrial',
	COPY_TEXT_FROM_TPA = '@pi:app:sdk:copy_text_from_tpa',
	REQUEST_NATIVE_PERMISSION = '@pi:app:sdk:request_native_permission',
	OPEN_URL_IN_SYSTEM_BROWSER = '@pi:app:sdk:open_url_in_system_browser',
	TRACK_LOCATION = '@pi:app:sdk:track_location',
}
